version: '3'

services:

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: diltheyaislan/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: diltheyaislan/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports:
      - "8080:80"
  
networks:
  laranet:
    driver: bridge